In [2]:
import numpy as np
import pandas as pd
import itertools
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline
import types
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_9c281a5ae54f498f8ae9ea6f2f7f55e8 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='515ykHduIh7vyYb-5GoOnFqjzwKIe0pOegyvyJ5MEDiZ',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_9c281a5ae54f498f8ae9ea6f2f7f55e8.get_object(Bucket='capstone-donotdelete-pr-gz54ejc8ywt7ti',Key='Data-Collisions.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df = pd.read_csv(body)
df.head(7)
# capstone project

/opt/conda/envs/Python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,SEVERITYCODE,X,Y,OBJECTID,INCKEY,COLDETKEY,REPORTNO,STATUS,ADDRTYPE,INTKEY,...,ROADCOND,LIGHTCOND,PEDROWNOTGRNT,SDOTCOLNUM,SPEEDING,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR
0,2,-122.323148,47.703140,1,1307,1307,3502005,Matched,Intersection,37475.0,...,Wet,Daylight,NaN,NaN,NaN,10,Entering at angle,0,0,N
1,1,-122.347294,47.647172,2,52200,52200,2607959,Matched,Block,NaN,...,Wet,Dark - Street Lights On,NaN,6354039.0,NaN,11,From same direction - both going straight - bo...,0,0,N
2,1,-122.334540,47.607871,3,26700,26700,1482393,Matched,Block,NaN,...,Dry,Daylight,NaN,4323031.0,NaN,32,One parked--one moving,0,0,N
3,1,-122.334803,47.604803,4,1144,1144,3503937,Matched,Block,NaN,...,Dry,Daylight,NaN,NaN,NaN,23,From same direction - all others,0,0,N
4,2,-122.306426,47.545739,5,17700,17700,1807429,Matched,Intersection,34387.0,...,Wet,Daylight,NaN,4028032.0,NaN,10,Entering at angle,0,0,N
5,1,-122.387598,47.690575,6,320840,322340,E919477,Matched,Intersection,36974.0,...,Dry,Daylight,NaN,NaN,NaN,10,Entering at angle,0,0,N
6,1,-122.338485,47.618534,7,83300,83300,3282542,Matched,Intersection,29510.0,...,Wet,Daylight,NaN,8344002.0,NaN,10,Entering at angle,0,0,N

In [3]:
df['SEVERITYCODE'].value_counts()

1    136485
2     58188
Name: SEVERITYCODE, dtype: int64

In [4]:
df.dtypes

SEVERITYCODE        int64
X                 float64
Y                 float64
OBJECTID            int64
INCKEY              int64
COLDETKEY           int64
REPORTNO           object
STATUS             object
ADDRTYPE           object
INTKEY            float64
LOCATION           object
EXCEPTRSNCODE      object
EXCEPTRSNDESC      object
SEVERITYCODE.1      int64
SEVERITYDESC       object
COLLISIONTYPE      object
PERSONCOUNT         int64
PEDCOUNT            int64
PEDCYLCOUNT         int64
VEHCOUNT            int64
INCDATE            object
INCDTTM            object
JUNCTIONTYPE       object
SDOT_COLCODE        int64
SDOT_COLDESC       object
INATTENTIONIND     object
UNDERINFL          object
WEATHER            object
ROADCOND           object
LIGHTCOND          object
PEDROWNOTGRNT      object
SDOTCOLNUM        float64
SPEEDING           object
ST_COLCODE         object
ST_COLDESC         object
SEGLANEKEY          int64
CROSSWALKKEY        int64
HITPARKEDCAR       object
dtype: object

In [5]:
df1=df[['SEVERITYCODE','WEATHER','ROADCOND','LIGHTCOND']]
df1.head()

   SEVERITYCODE   WEATHER ROADCOND                LIGHTCOND
0             2  Overcast      Wet                 Daylight
1             1   Raining      Wet  Dark - Street Lights On
2             1  Overcast      Dry                 Daylight
3             1     Clear      Dry                 Daylight
4             2   Raining      Wet                 Daylight

In [6]:
df1['LIGHTCOND'].value_counts()

Daylight                    116137
Dark - Street Lights On      48507
Unknown                      13473
Dusk                          5902
Dawn                          2502
Dark - No Street Lights       1537
Dark - Street Lights Off      1199
Other                          235
Dark - Unknown Lighting         11
Name: LIGHTCOND, dtype: int64

In [7]:
df1.replace("", np.nan, inplace = True)
missing_data = df1.isnull()
missing_data.head(16)

/opt/conda/envs/Python36/lib/python3.6/site-packages/pandas/core/frame.py:4042: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  method=method)

    SEVERITYCODE  WEATHER  ROADCOND  LIGHTCOND
0          False    False     False      False
1          False    False     False      False
2          False    False     False      False
3          False    False     False      False
4          False    False     False      False
5          False    False     False      False
6          False    False     False      False
7          False    False     False      False
8          False    False     False      False
9          False    False     False      False
10         False    False     False      False
11         False    False     False      False
12         False    False     False      False
13         False    False     False      False
14         False    False     False      False
15         False     True      True       True

In [8]:

for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

SEVERITYCODE
False    194673
Name: SEVERITYCODE, dtype: int64

WEATHER
False    189592
True       5081
Name: WEATHER, dtype: int64

ROADCOND
False    189661
True       5012
Name: ROADCOND, dtype: int64

LIGHTCOND
False    189503
True       5170
Name: LIGHTCOND, dtype: int64

In [9]:
df1.dropna(subset=["LIGHTCOND"], axis=0, inplace=True)

# reset index, because we droped two rows
df1.reset_index(drop=True, inplace=True)
df1.head(16)

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

    SEVERITYCODE   WEATHER ROADCOND                LIGHTCOND
0              2  Overcast      Wet                 Daylight
1              1   Raining      Wet  Dark - Street Lights On
2              1  Overcast      Dry                 Daylight
3              1     Clear      Dry                 Daylight
4              2   Raining      Wet                 Daylight
5              1     Clear      Dry                 Daylight
6              1   Raining      Wet                 Daylight
7              2     Clear      Dry                 Daylight
8              1     Clear      Dry                 Daylight
9              2     Clear      Dry                 Daylight
10             1  Overcast      Dry                 Daylight
11             1     Clear      Dry                 Daylight
12             1   Raining      Wet  Dark - Street Lights On
13             1   Raining      Wet  Dark - No Street Lights
14             2     Clear      Dry  Dark - Street Lights On
15             2  Overcast      Dry                 Daylight

In [10]:
missing_data = df1.isnull()
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

SEVERITYCODE
False    189503
Name: SEVERITYCODE, dtype: int64

WEATHER
False    189381
True        122
Name: WEATHER, dtype: int64

ROADCOND
False    189443
True         60
Name: ROADCOND, dtype: int64

LIGHTCOND
False    189503
Name: LIGHTCOND, dtype: int64

In [11]:
df1.dropna(subset=["ROADCOND"], axis=0, inplace=True)
df1.dropna(subset=["WEATHER"], axis=0, inplace=True)
# reset index, because we droped two rows
df1.reset_index(drop=True, inplace=True)

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [12]:
missing_data = df1.isnull()
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

SEVERITYCODE
False    189337
Name: SEVERITYCODE, dtype: int64

WEATHER
False    189337
Name: WEATHER, dtype: int64

ROADCOND
False    189337
Name: ROADCOND, dtype: int64

LIGHTCOND
False    189337
Name: LIGHTCOND, dtype: int64

In [13]:
cleanup_nums = {"WEATHER":     {"Clear": 1, "Raining": 2, "Overcast":3, "Unknown":4, "Snowing":5, "Other":6, "Fog/Smog/Smoke":7, "Sleet/Hail/Freezing Rain":8, "Blowing Sand/Dirt":9, "Severe Crosswind":10, "Partly Cloudy":11 },
                "ROADCOND": {"Dry": 1, "Wet": 2, "Unknown": 3, "Ice": 4, "Snow/Slush": 5, "Other": 6, "Standing Water":7, "Sand/Mud/Dirt":8, "Oil":9 },
                "LIGHTCOND": {"Daylight":1, "Dark - Street Lights On":2, "Unknown":3,"Dusk":4, "Dawn":5, "Dark - No Street Lights":6,"Dark - Street Lights Off":7, "Other":8, "Dark - Unknown Lighting":9 }}
df1.replace(cleanup_nums, inplace=True)
df1.head(6)

/opt/conda/envs/Python36/lib/python3.6/site-packages/pandas/core/generic.py:6517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  regex=regex)

   SEVERITYCODE  WEATHER  ROADCOND  LIGHTCOND
0             2        3         2          1
1             1        2         2          2
2             1        3         1          1
3             1        1         1          1
4             2        2         2          1
5             1        1         1          1

In [14]:
X = df1[['WEATHER','ROADCOND','LIGHTCOND']] .values.astype(float)
X[0:5]

array([[3., 2., 1.],
       [2., 2., 2.],
       [3., 1., 1.],
       [1., 1., 1.],
       [2., 2., 1.]])

In [15]:
y = df1['SEVERITYCODE'].values.astype(float)
y[0:5]

array([2., 1., 1., 1., 2.])

In [16]:
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))
X[0:5]

array([[ 1.10587178,  0.70875343, -0.59511457],
       [ 0.20504641,  0.70875343,  0.34710496],
       [ 1.10587178, -0.60855849, -0.59511457],
       [-0.69577897, -0.60855849, -0.59511457],
       [ 0.20504641,  0.70875343, -0.59511457]])

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (132535, 3) (132535,)
Test set: (56802, 3) (56802,)

In [31]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
k = 10
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
yhat = neigh.predict(X_test)
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

Train set Accuracy:  0.698713547364847
Test set Accuracy:  0.6982500616175487


Ks = 15
mean_acc = np.zeros((Ks-1))
std_acc = np.zeros((Ks-1))
ConfustionMx = [];
for n in range(1,Ks):
    
    #Train Model and Predict  
    neigh = KNeighborsClassifier(n_neighbors = n).fit(X_train,y_train)
    yhat=neigh.predict(X_test)
    mean_acc[n-1] = metrics.accuracy_score(y_test, yhat)

    
    std_acc[n-1]=np.std(yhat==y_test)/np.sqrt(yhat.shape[0])

mean_acc

plt.plot(range(1,Ks),mean_acc,'g')
plt.fill_between(range(1,Ks),mean_acc - 1 * std_acc,mean_acc + 1 * std_acc, alpha=0.10)
plt.legend(('Accuracy ', '+/- 3xstd'))
plt.ylabel('Accuracy ')
plt.xlabel('Number of Neighbours (K)')
plt.tight_layout()
plt.show()

In [18]:
#print( "The best accuracy was with", mean_acc.max(), "with k=", mean_acc.argmax()+1)

In [32]:
from sklearn.metrics import jaccard_similarity_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss

In [33]:
yhat = neigh.predict(X_test)
print("KNN Jaccard index: %.2f" % jaccard_similarity_score(y_test, yhat))
print("KNN F1-score: %.2f" % f1_score(y_test,yhat, average='weighted') )

KNN Jaccard index: 0.70
KNN F1-score: 0.57

In [47]:
from sklearn.tree import DecisionTreeClassifier
severityTree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
severityTree # it shows the default parameters
severityTree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [49]:
yhat = severityTree.predict(X_test)
print (yhat [0:5])
print (y_test [0:5])
print("Train set Accuracy: ", metrics.accuracy_score(y_train, severityTree.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 2.]
Train set Accuracy:  0.69874372807183
Test set Accuracy:  0.6985141368261681

In [36]:
yhat = severityTree.predict(X_test)
print("decision tree Jaccard index: %.2f" % jaccard_similarity_score(y_test, yhat))
print("decision tree F1-score: %.2f" % f1_score(y_test, yhat, average='weighted') )

decision tree Jaccard index: 0.70
decision tree F1-score: 0.57

/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [37]:
import matplotlib.pyplot as plt
#print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_test, yhat))

In [50]:
import pylab as pl
import scipy.optimize as opt

In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [52]:
yhat = LR.predict(X_test)
yhat[0:5]
print("Train set Accuracy: ", metrics.accuracy_score(y_train, LR.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

Train set Accuracy:  0.69874372807183
Test set Accuracy:  0.6985141368261681

In [54]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob[0:5]

array([[0.64754333, 0.35245667],
       [0.82778258, 0.17221742],
       [0.73678675, 0.26321325],
       [0.75931302, 0.24068698],
       [0.64754333, 0.35245667]])

In [42]:
yhat = LR.predict(X_test)
yhat_prob = LR.predict_proba(X_test)
print("LR Jaccard index: %.2f" % jaccard_similarity_score(y_test, yhat))
print("LR F1-score: %.2f" % f1_score(y_test, yhat, average='weighted') )
print("LR LogLoss: %.2f" % log_loss(y_test, yhat_prob))

LR Jaccard index: 0.70
LR F1-score: 0.57
LR LogLoss: 0.60

/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [64]:
| Algorithm          | Jaccard | F1-score | LogLoss |
|--------------------|---------|----------|---------|
| KNN                | 0.70       |0.57      | NA      |
| Decision Tree      | 0.70      | 0.57       | NA      |
| LogisticRegression | 0.70       |0.57       | 0.60      |

SyntaxError: invalid syntax (<ipython-input-64-a01bd17bdfb3>, line 1)